app:
    resource: '@AppBundle/Controller/'
    type: annotation

user_list:
    path:      /user
    defaults:  { _controller: AppBundle:User:list }

user_show:
    path:      /user/{slug}
    defaults:  { _controller: AppBundle:User:show }